#pragma once

const int WIDTH = 1280;
const int HEIGHT = 720;

const int TICKRATE = 100;
const int MAX_FRAMESKIP = 5;

enum BuildingType {FACTORY, PORT, AIRPORT, CITY, HQ};
enum Action {ANONE, CAPTURE, CREATE_UNIT};
enum UnitType {UNONE, SOLDIER, MECH, APC, TANK, HTANK, RECON, ARTILERY, ROCKETS, AA, MISSILES, BSHIP, CRUISER, LANDER, SUB, FIGHTER, BOMBER, BCHOPPER, TCHOPPER};
enum Side {SNONE, RED, BLUE};
enum Terrain {GRASS, BEACH, ROAD, WATER, MOUNTAIN, FOREST};